# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    app_bundle.service.listener:
        class: MA\LrmBundle\Listener\LoadDataListener
        arguments: [name: 'kernel.event_listener', event: 'fullcalendar.set_data', method: loadData]
