ma_lrm_emploi_index:
    path:     /
    defaults: { _controller: "MALrmBundle:Emploi:index" }
    methods:  GET

ma_lrm_emploi_show:
    path:     /{id}/show
    defaults: { _controller: "MALrmBundle:Emploi:show" }
    methods:  GET

ma_lrm_emploi_new:
    path:     /new
    defaults: { _controller: "MALrmBundle:Emploi:new" }
    methods:  [GET, POST]

ma_lrm_emploi_edit:
    path:     /{id}/edit
    defaults: { _controller: "MALrmBundle:Emploi:edit" }
    methods:  [GET, POST]

#ma_lrm_emploi_delete:
#    path:     /{id}/delete
#    defaults: { _controller: "MALrmBundle:Emploi:delete" }
#    methods:  DELETE

ma_lrm_emploi_delete:
    path:     /{id}/delete
    defaults: { _controller: "MALrmBundle:Emploi:delete" }
    methods:  [GET, POST, DELETE]

ma_lrm_emploi_ville:
    path:     /new/ville/{string}
    defaults: { _controller: "MALrmBundle:Emploi:ville" }
    methods:  [GET, POST]