<?php

namespace Proxies\__CG__\MA\LrmBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Departement extends \MA\LrmBundle\Entity\Departement implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'MA\\LrmBundle\\Entity\\Departement' . "\0" . 'id', '' . "\0" . 'MA\\LrmBundle\\Entity\\Departement' . "\0" . 'departementCode', '' . "\0" . 'MA\\LrmBundle\\Entity\\Departement' . "\0" . 'departementNom', '' . "\0" . 'MA\\LrmBundle\\Entity\\Departement' . "\0" . 'departementNomUppercase', '' . "\0" . 'MA\\LrmBundle\\Entity\\Departement' . "\0" . 'departementSlug', '' . "\0" . 'MA\\LrmBundle\\Entity\\Departement' . "\0" . 'departementNomSoundex', '' . "\0" . 'MA\\LrmBundle\\Entity\\Departement' . "\0" . 'pays'];
        }

        return ['__isInitialized__', '' . "\0" . 'MA\\LrmBundle\\Entity\\Departement' . "\0" . 'id', '' . "\0" . 'MA\\LrmBundle\\Entity\\Departement' . "\0" . 'departementCode', '' . "\0" . 'MA\\LrmBundle\\Entity\\Departement' . "\0" . 'departementNom', '' . "\0" . 'MA\\LrmBundle\\Entity\\Departement' . "\0" . 'departementNomUppercase', '' . "\0" . 'MA\\LrmBundle\\Entity\\Departement' . "\0" . 'departementSlug', '' . "\0" . 'MA\\LrmBundle\\Entity\\Departement' . "\0" . 'departementNomSoundex', '' . "\0" . 'MA\\LrmBundle\\Entity\\Departement' . "\0" . 'pays'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Departement $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function setDepartementCode($departementCode)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDepartementCode', [$departementCode]);

        return parent::setDepartementCode($departementCode);
    }

    /**
     * {@inheritDoc}
     */
    public function getDepartementCode()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDepartementCode', []);

        return parent::getDepartementCode();
    }

    /**
     * {@inheritDoc}
     */
    public function setDepartementNom($departementNom)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDepartementNom', [$departementNom]);

        return parent::setDepartementNom($departementNom);
    }

    /**
     * {@inheritDoc}
     */
    public function getDepartementNom()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDepartementNom', []);

        return parent::getDepartementNom();
    }

    /**
     * {@inheritDoc}
     */
    public function setDepartementNomUppercase($departementNomUppercase)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDepartementNomUppercase', [$departementNomUppercase]);

        return parent::setDepartementNomUppercase($departementNomUppercase);
    }

    /**
     * {@inheritDoc}
     */
    public function getDepartementNomUppercase()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDepartementNomUppercase', []);

        return parent::getDepartementNomUppercase();
    }

    /**
     * {@inheritDoc}
     */
    public function setDepartementSlug($departementSlug)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDepartementSlug', [$departementSlug]);

        return parent::setDepartementSlug($departementSlug);
    }

    /**
     * {@inheritDoc}
     */
    public function getDepartementSlug()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDepartementSlug', []);

        return parent::getDepartementSlug();
    }

    /**
     * {@inheritDoc}
     */
    public function setDepartementNomSoundex($departementNomSoundex)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDepartementNomSoundex', [$departementNomSoundex]);

        return parent::setDepartementNomSoundex($departementNomSoundex);
    }

    /**
     * {@inheritDoc}
     */
    public function getDepartementNomSoundex()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDepartementNomSoundex', []);

        return parent::getDepartementNomSoundex();
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setPays(\MA\LrmBundle\Entity\Pays $pays = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPays', [$pays]);

        return parent::setPays($pays);
    }

    /**
     * {@inheritDoc}
     */
    public function getPays()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPays', []);

        return parent::getPays();
    }

}
