
ma_lrm_accueil:
    path:     /accueil
    defaults:  { _controller: MALrmBundle:Index:index }
#    methods:  [GET, POST]

ma_lrm_register:
    path:     /register
    defaults:  { _controller: MAUserBundle:Registration:register }

ma_lrm_calendar:
    path:     /accueil/calendar
    defaults: { _controller: MALrmBundle:Index:load }
    methods:  [GET, POST]

ma_lrm_calendar_resize:
    path:     /accueil/calendar/resize
    defaults: { _controller: MALrmBundle:Index:resizeEvent }
    methods:  [GET, POST]

ma_lrm_calendar_drop:
    path:     /accueil/calendar/drop
    defaults: { _controller: MALrmBundle:Index:dropEvent }
    methods:  [GET, POST]

ma_lrm_calendar_delete:
    path:     /accueil/calendar/delete
    defaults: { _controller: MALrmBundle:Index:deleteEvent }
    methods:  [GET, POST]

ma_lrm_calendar_selectUser:
    path:     /accueil/calendar/select/user
    defaults: { _controller: MALrmBundle:Index:selectUser }
    methods:  [GET, POST]

ma_lrm_calendar_editEvent:
    path:     /accueil/calendar/edit/title
    defaults: { _controller: MALrmBundle:Index:editEvent }
    methods:  [GET, POST]




#ma_lrm_calendar_new:
#    path:     /accueil
#    defaults: { _controller: "MALrmBundle:Index:new" }
#    methods:  [GET, POST]

