ma_lrm_accueil:
    path:     /accueil
    defaults:  { _controller: MALrmBundle:Index:index }
#    methods:  [GET, POST]

ma_lrm_register:
    path:     /register
    defaults:  { _controller: MAUserBundle:Registration:register }

ma_lrm_calendar:
    path:     /accueil/calendar
    defaults: { _controller: "MALrmBundle:Index:load" }
    methods:  [GET, POST]

#ma_lrm_calendar_new:
#    path:     /accueil
#    defaults: { _controller: "MALrmBundle:Index:new" }
#    methods:  [GET, POST]

