ma_lrm_accueil:
    path:     /accueil
    defaults:  { _controller: MALrmBundle:Index:index }

ma_lrm_register:
    path:     /register
    defaults:  { _controller: MAUserBundle:Registration:register }

ma_lrm_calendar:
    path:     /accueil/calendar
    defaults: { _controller: "MALrmBundle:Index:load" }
    methods:  [GET, POST]
