<?php

namespace MA\LrmBundle\Repository;

/**
 * GestionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GestionRepository extends \Doctrine\ORM\EntityRepository
{
    public function countPostePourvu($idEmploi)
    {
        $query = $this->_em->createQuery('SELECT g FROM MALrmBundle:Gestion g WHERE g.emploi = '.$idEmploi.'');

        $results = $query->getResult();
        
        return $results;
    }
}
