<?php

namespace MA\LrmBundle\Repository;

/**
 * GestionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GestionRepository extends \Doctrine\ORM\EntityRepository
{
}
