<?php

namespace MA\LrmBundle\Repository;

/**
 * GestionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GestionRepository extends \Doctrine\ORM\EntityRepository
{
    public function countPostePourvu($idEmploi)
    {
        $query = $this->_em->createQuery('SELECT g FROM MALrmBundle:Gestion g WHERE g.emploi = '.$idEmploi.'');

        $results = $query->getResult();
        
        return $results;
    }

    public function editEtat($idClient, $etat)
    {
        return $this
            ->createQueryBuilder('c')
            ->update('MALrmBundle:Client', 'e')
            ->set('e.etat', '?1')
            ->where('e.id = ?2')
            ->setParameter(1, $etat)
            ->setParameter(2, $idClient)
            ->getQuery()
            ->getResult();
    }
}
