<?php

namespace MA\LrmBundle\Repository;

/**
 * VillesFranceFreeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VillesFranceFreeRepository extends \Doctrine\ORM\EntityRepository
{
    /*
     * Return villes par ordre alphabet
     */
    public function findAllOrderByName()
    {
        $qb = $this->createQueryBuilder('v');

        $qb->orderBy('v.villeNomReel', 'ASC');

        return $qb
            ->getQuery()
            ->getResult();
    }

    public function autoComplete($string)
    {
        
        $query = $this->getEntityManager()
            ->createQuery("
	            SELECT v FROM MALrmBundle:VillesFranceFree v
	            WHERE v.villeNomReel LIKE :string "
            );
        $query->setParameter('string', $string.'%');

        return $query->getResult();


    }
}
