<?php

namespace Proxies\__CG__\MA\LrmBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Emploi extends \MA\LrmBundle\Entity\Emploi implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'MA\\LrmBundle\\Entity\\Emploi' . "\0" . 'id', '' . "\0" . 'MA\\LrmBundle\\Entity\\Emploi' . "\0" . 'intitule', '' . "\0" . 'MA\\LrmBundle\\Entity\\Emploi' . "\0" . 'contrat', '' . "\0" . 'MA\\LrmBundle\\Entity\\Emploi' . "\0" . 'description', '' . "\0" . 'MA\\LrmBundle\\Entity\\Emploi' . "\0" . 'siteParution', '' . "\0" . 'MA\\LrmBundle\\Entity\\Emploi' . "\0" . 'villeCodePostal', '' . "\0" . 'MA\\LrmBundle\\Entity\\Emploi' . "\0" . 'villeActivite', '' . "\0" . 'MA\\LrmBundle\\Entity\\Emploi' . "\0" . 'client', '' . "\0" . 'MA\\LrmBundle\\Entity\\Emploi' . "\0" . 'nombrePoste', '' . "\0" . 'MA\\LrmBundle\\Entity\\Emploi' . "\0" . 'dateCreation'];
        }

        return ['__isInitialized__', '' . "\0" . 'MA\\LrmBundle\\Entity\\Emploi' . "\0" . 'id', '' . "\0" . 'MA\\LrmBundle\\Entity\\Emploi' . "\0" . 'intitule', '' . "\0" . 'MA\\LrmBundle\\Entity\\Emploi' . "\0" . 'contrat', '' . "\0" . 'MA\\LrmBundle\\Entity\\Emploi' . "\0" . 'description', '' . "\0" . 'MA\\LrmBundle\\Entity\\Emploi' . "\0" . 'siteParution', '' . "\0" . 'MA\\LrmBundle\\Entity\\Emploi' . "\0" . 'villeCodePostal', '' . "\0" . 'MA\\LrmBundle\\Entity\\Emploi' . "\0" . 'villeActivite', '' . "\0" . 'MA\\LrmBundle\\Entity\\Emploi' . "\0" . 'client', '' . "\0" . 'MA\\LrmBundle\\Entity\\Emploi' . "\0" . 'nombrePoste', '' . "\0" . 'MA\\LrmBundle\\Entity\\Emploi' . "\0" . 'dateCreation'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Emploi $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function setIntitule($intitule)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIntitule', [$intitule]);

        return parent::setIntitule($intitule);
    }

    /**
     * {@inheritDoc}
     */
    public function getIntitule()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIntitule', []);

        return parent::getIntitule();
    }

    /**
     * {@inheritDoc}
     */
    public function setContrat($contrat)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setContrat', [$contrat]);

        return parent::setContrat($contrat);
    }

    /**
     * {@inheritDoc}
     */
    public function getContrat()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getContrat', []);

        return parent::getContrat();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescription($description)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescription', [$description]);

        return parent::setDescription($description);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescription()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescription', []);

        return parent::getDescription();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateCreation($dateCreation)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateCreation', [$dateCreation]);

        return parent::setDateCreation($dateCreation);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateCreation()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateCreation', []);

        return parent::getDateCreation();
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setClient(\MA\LrmBundle\Entity\Client $client = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setClient', [$client]);

        return parent::setClient($client);
    }

    /**
     * {@inheritDoc}
     */
    public function getClient()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getClient', []);

        return parent::getClient();
    }

    /**
     * {@inheritDoc}
     */
    public function setSiteParution($siteParution)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSiteParution', [$siteParution]);

        return parent::setSiteParution($siteParution);
    }

    /**
     * {@inheritDoc}
     */
    public function getSiteParution()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSiteParution', []);

        return parent::getSiteParution();
    }

    /**
     * {@inheritDoc}
     */
    public function setVilleCodePostal($villeCodePostal)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVilleCodePostal', [$villeCodePostal]);

        return parent::setVilleCodePostal($villeCodePostal);
    }

    /**
     * {@inheritDoc}
     */
    public function getVilleCodePostal()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVilleCodePostal', []);

        return parent::getVilleCodePostal();
    }

    /**
     * {@inheritDoc}
     */
    public function setVilleActivite($villeActivite)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVilleActivite', [$villeActivite]);

        return parent::setVilleActivite($villeActivite);
    }

    /**
     * {@inheritDoc}
     */
    public function getVilleActivite()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVilleActivite', []);

        return parent::getVilleActivite();
    }

    /**
     * {@inheritDoc}
     */
    public function setNombrePoste($nombrePoste)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNombrePoste', [$nombrePoste]);

        return parent::setNombrePoste($nombrePoste);
    }

    /**
     * {@inheritDoc}
     */
    public function getNombrePoste()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNombrePoste', []);

        return parent::getNombrePoste();
    }

}
