<?php

namespace Proxies\__CG__\MA\LrmBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class VillesFranceFree extends \MA\LrmBundle\Entity\VillesFranceFree implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'MA\\LrmBundle\\Entity\\VillesFranceFree' . "\0" . 'id', '' . "\0" . 'MA\\LrmBundle\\Entity\\VillesFranceFree' . "\0" . 'villeDepartement', '' . "\0" . 'MA\\LrmBundle\\Entity\\VillesFranceFree' . "\0" . 'villeSlug', '' . "\0" . 'MA\\LrmBundle\\Entity\\VillesFranceFree' . "\0" . 'villeNom', '' . "\0" . 'MA\\LrmBundle\\Entity\\VillesFranceFree' . "\0" . 'villeNomSimple', '' . "\0" . 'MA\\LrmBundle\\Entity\\VillesFranceFree' . "\0" . 'villeNomReel', '' . "\0" . 'MA\\LrmBundle\\Entity\\VillesFranceFree' . "\0" . 'villeCodePostal', '' . "\0" . 'MA\\LrmBundle\\Entity\\VillesFranceFree' . "\0" . 'villeCodeCommune', '' . "\0" . 'MA\\LrmBundle\\Entity\\VillesFranceFree' . "\0" . 'villeArrondissement', '' . "\0" . 'MA\\LrmBundle\\Entity\\VillesFranceFree' . "\0" . 'villeCanton', '' . "\0" . 'MA\\LrmBundle\\Entity\\VillesFranceFree' . "\0" . 'villeLongitudeDeg', '' . "\0" . 'MA\\LrmBundle\\Entity\\VillesFranceFree' . "\0" . 'villeLatitudeDeg', '' . "\0" . 'MA\\LrmBundle\\Entity\\VillesFranceFree' . "\0" . 'villeLongitudeGrd', '' . "\0" . 'MA\\LrmBundle\\Entity\\VillesFranceFree' . "\0" . 'villeLatitudeGrd', '' . "\0" . 'MA\\LrmBundle\\Entity\\VillesFranceFree' . "\0" . 'villeLongitudeDms', '' . "\0" . 'MA\\LrmBundle\\Entity\\VillesFranceFree' . "\0" . 'villeLatitudeDms', '' . "\0" . 'MA\\LrmBundle\\Entity\\VillesFranceFree' . "\0" . 'villeZmin', '' . "\0" . 'MA\\LrmBundle\\Entity\\VillesFranceFree' . "\0" . 'villeZmax', '' . "\0" . 'MA\\LrmBundle\\Entity\\VillesFranceFree' . "\0" . 'departement'];
        }

        return ['__isInitialized__', '' . "\0" . 'MA\\LrmBundle\\Entity\\VillesFranceFree' . "\0" . 'id', '' . "\0" . 'MA\\LrmBundle\\Entity\\VillesFranceFree' . "\0" . 'villeDepartement', '' . "\0" . 'MA\\LrmBundle\\Entity\\VillesFranceFree' . "\0" . 'villeSlug', '' . "\0" . 'MA\\LrmBundle\\Entity\\VillesFranceFree' . "\0" . 'villeNom', '' . "\0" . 'MA\\LrmBundle\\Entity\\VillesFranceFree' . "\0" . 'villeNomSimple', '' . "\0" . 'MA\\LrmBundle\\Entity\\VillesFranceFree' . "\0" . 'villeNomReel', '' . "\0" . 'MA\\LrmBundle\\Entity\\VillesFranceFree' . "\0" . 'villeCodePostal', '' . "\0" . 'MA\\LrmBundle\\Entity\\VillesFranceFree' . "\0" . 'villeCodeCommune', '' . "\0" . 'MA\\LrmBundle\\Entity\\VillesFranceFree' . "\0" . 'villeArrondissement', '' . "\0" . 'MA\\LrmBundle\\Entity\\VillesFranceFree' . "\0" . 'villeCanton', '' . "\0" . 'MA\\LrmBundle\\Entity\\VillesFranceFree' . "\0" . 'villeLongitudeDeg', '' . "\0" . 'MA\\LrmBundle\\Entity\\VillesFranceFree' . "\0" . 'villeLatitudeDeg', '' . "\0" . 'MA\\LrmBundle\\Entity\\VillesFranceFree' . "\0" . 'villeLongitudeGrd', '' . "\0" . 'MA\\LrmBundle\\Entity\\VillesFranceFree' . "\0" . 'villeLatitudeGrd', '' . "\0" . 'MA\\LrmBundle\\Entity\\VillesFranceFree' . "\0" . 'villeLongitudeDms', '' . "\0" . 'MA\\LrmBundle\\Entity\\VillesFranceFree' . "\0" . 'villeLatitudeDms', '' . "\0" . 'MA\\LrmBundle\\Entity\\VillesFranceFree' . "\0" . 'villeZmin', '' . "\0" . 'MA\\LrmBundle\\Entity\\VillesFranceFree' . "\0" . 'villeZmax', '' . "\0" . 'MA\\LrmBundle\\Entity\\VillesFranceFree' . "\0" . 'departement'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (VillesFranceFree $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function setVilleDepartement($villeDepartement)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVilleDepartement', [$villeDepartement]);

        return parent::setVilleDepartement($villeDepartement);
    }

    /**
     * {@inheritDoc}
     */
    public function getVilleDepartement()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVilleDepartement', []);

        return parent::getVilleDepartement();
    }

    /**
     * {@inheritDoc}
     */
    public function setVilleSlug($villeSlug)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVilleSlug', [$villeSlug]);

        return parent::setVilleSlug($villeSlug);
    }

    /**
     * {@inheritDoc}
     */
    public function getVilleSlug()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVilleSlug', []);

        return parent::getVilleSlug();
    }

    /**
     * {@inheritDoc}
     */
    public function setVilleNom($villeNom)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVilleNom', [$villeNom]);

        return parent::setVilleNom($villeNom);
    }

    /**
     * {@inheritDoc}
     */
    public function getVilleNom()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVilleNom', []);

        return parent::getVilleNom();
    }

    /**
     * {@inheritDoc}
     */
    public function setVilleNomSimple($villeNomSimple)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVilleNomSimple', [$villeNomSimple]);

        return parent::setVilleNomSimple($villeNomSimple);
    }

    /**
     * {@inheritDoc}
     */
    public function getVilleNomSimple()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVilleNomSimple', []);

        return parent::getVilleNomSimple();
    }

    /**
     * {@inheritDoc}
     */
    public function setVilleNomReel($villeNomReel)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVilleNomReel', [$villeNomReel]);

        return parent::setVilleNomReel($villeNomReel);
    }

    /**
     * {@inheritDoc}
     */
    public function getVilleNomReel()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVilleNomReel', []);

        return parent::getVilleNomReel();
    }

    /**
     * {@inheritDoc}
     */
    public function setVilleCodePostal($villeCodePostal)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVilleCodePostal', [$villeCodePostal]);

        return parent::setVilleCodePostal($villeCodePostal);
    }

    /**
     * {@inheritDoc}
     */
    public function getVilleCodePostal()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVilleCodePostal', []);

        return parent::getVilleCodePostal();
    }

    /**
     * {@inheritDoc}
     */
    public function setVilleCodeCommune($villeCodeCommune)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVilleCodeCommune', [$villeCodeCommune]);

        return parent::setVilleCodeCommune($villeCodeCommune);
    }

    /**
     * {@inheritDoc}
     */
    public function getVilleCodeCommune()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVilleCodeCommune', []);

        return parent::getVilleCodeCommune();
    }

    /**
     * {@inheritDoc}
     */
    public function setVilleArrondissement($villeArrondissement)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVilleArrondissement', [$villeArrondissement]);

        return parent::setVilleArrondissement($villeArrondissement);
    }

    /**
     * {@inheritDoc}
     */
    public function getVilleArrondissement()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVilleArrondissement', []);

        return parent::getVilleArrondissement();
    }

    /**
     * {@inheritDoc}
     */
    public function setVilleCanton($villeCanton)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVilleCanton', [$villeCanton]);

        return parent::setVilleCanton($villeCanton);
    }

    /**
     * {@inheritDoc}
     */
    public function getVilleCanton()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVilleCanton', []);

        return parent::getVilleCanton();
    }

    /**
     * {@inheritDoc}
     */
    public function setVilleLongitudeDeg($villeLongitudeDeg)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVilleLongitudeDeg', [$villeLongitudeDeg]);

        return parent::setVilleLongitudeDeg($villeLongitudeDeg);
    }

    /**
     * {@inheritDoc}
     */
    public function getVilleLongitudeDeg()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVilleLongitudeDeg', []);

        return parent::getVilleLongitudeDeg();
    }

    /**
     * {@inheritDoc}
     */
    public function setVilleLatitudeDeg($villeLatitudeDeg)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVilleLatitudeDeg', [$villeLatitudeDeg]);

        return parent::setVilleLatitudeDeg($villeLatitudeDeg);
    }

    /**
     * {@inheritDoc}
     */
    public function getVilleLatitudeDeg()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVilleLatitudeDeg', []);

        return parent::getVilleLatitudeDeg();
    }

    /**
     * {@inheritDoc}
     */
    public function setVilleLongitudeGrd($villeLongitudeGrd)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVilleLongitudeGrd', [$villeLongitudeGrd]);

        return parent::setVilleLongitudeGrd($villeLongitudeGrd);
    }

    /**
     * {@inheritDoc}
     */
    public function getVilleLongitudeGrd()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVilleLongitudeGrd', []);

        return parent::getVilleLongitudeGrd();
    }

    /**
     * {@inheritDoc}
     */
    public function setVilleLatitudeGrd($villeLatitudeGrd)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVilleLatitudeGrd', [$villeLatitudeGrd]);

        return parent::setVilleLatitudeGrd($villeLatitudeGrd);
    }

    /**
     * {@inheritDoc}
     */
    public function getVilleLatitudeGrd()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVilleLatitudeGrd', []);

        return parent::getVilleLatitudeGrd();
    }

    /**
     * {@inheritDoc}
     */
    public function setVilleLongitudeDms($villeLongitudeDms)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVilleLongitudeDms', [$villeLongitudeDms]);

        return parent::setVilleLongitudeDms($villeLongitudeDms);
    }

    /**
     * {@inheritDoc}
     */
    public function getVilleLongitudeDms()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVilleLongitudeDms', []);

        return parent::getVilleLongitudeDms();
    }

    /**
     * {@inheritDoc}
     */
    public function setVilleLatitudeDms($villeLatitudeDms)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVilleLatitudeDms', [$villeLatitudeDms]);

        return parent::setVilleLatitudeDms($villeLatitudeDms);
    }

    /**
     * {@inheritDoc}
     */
    public function getVilleLatitudeDms()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVilleLatitudeDms', []);

        return parent::getVilleLatitudeDms();
    }

    /**
     * {@inheritDoc}
     */
    public function setVilleZmin($villeZmin)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVilleZmin', [$villeZmin]);

        return parent::setVilleZmin($villeZmin);
    }

    /**
     * {@inheritDoc}
     */
    public function getVilleZmin()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVilleZmin', []);

        return parent::getVilleZmin();
    }

    /**
     * {@inheritDoc}
     */
    public function setVilleZmax($villeZmax)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVilleZmax', [$villeZmax]);

        return parent::setVilleZmax($villeZmax);
    }

    /**
     * {@inheritDoc}
     */
    public function getVilleZmax()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVilleZmax', []);

        return parent::getVilleZmax();
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setDepartement(\MA\LrmBundle\Entity\Departement $departement = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDepartement', [$departement]);

        return parent::setDepartement($departement);
    }

    /**
     * {@inheritDoc}
     */
    public function getDepartement()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDepartement', []);

        return parent::getDepartement();
    }

}
